# Site settings
title: Rough Drafts
description: "Nithin's blog"
baseurl: ""
url: "https://nithink.dev"
github_username: aalavandhan
twitter_username: aalavandhan84

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

header_pages:
  - research.markdown
  - about.markdown

plugins:
  - jekyll-feed

exclude:
  - Makefile
  - threads
